
# The base URL of the site; the only required configuration variable.
base_url = "https://kuyapp.pages.dev"

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     author = "Famous author"
#
# author value will be available using {{ config.extra.author }} in templates
#
[extra]
